### ISSUE TITLE
Make text of content paragraphs left-justified, but not so far left

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#12]
See how the paragraphs are way to the left? Having them centered didn't work, so I changed them.

I want the text to be left justified... but not all the way left. Not so far. I want some kind of margin so it looks closer to the left edge of the diagrams. Can you do this?

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/42149/223876490-e85629ca-3a3c-4dd8-aa62-995c40caa0d7.png">

**Comment by sammjainn** [comment]
As per issue https://github.com/Graphlet-AI/graphlet-ai.github.io/issues/6
I just justified the content of the paragraphs. Please check if that looks good or you want to justify the content towards the left

**Comment by rjurney** [comment]
@sammjainn confirmed, justification looks ok. Content still not centered overall.
