### ISSUE TITLE
Heading text is too large

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#19]
Can you please reduce the font size on the (I think) H1 headers in this image? They are too big, look funny on my computer.

<img width="1904" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/3a0c3913-c02c-4ad1-a2dd-f6975a959cb4">

The text "Property graph factories build property graphs in 4 steps..." is too large. So are the other headings of this level. Can you make them smaller, and make the headings one level down like "Step 1) Extract, Transform, Load Datasets to a Common Format" smaller to accommodate the other change? They are a little too loud compared to the text. Make them bolder if you have to, if they get too small.

This is new work, not covered under the last statement of work, so you can bill me for it :)

Web browser: Chrome Version 113.0.5672.92 (Official Build) (x86_64)
OS: Mac OS X Ventura 13.3.1 (22E261)
State of mind: peaceful :)

**Comment by sammjainn** [comment]
I have fixed most of the sizing and responsiveness issues now. Please check them and let me know if it's all good, we can mark the issues as resolved
