### ISSUE TITLE
Add bullet points to list of software packages

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#21]
Can you please add bullet points to the left of this list? They don’t appear on desktop or mobile.

![E1B4A0DA-8563-4790-844A-3D596AE08C6F](https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/c0e69407-b02d-4728-854a-0aafadca5bf1)

**Comment by sammjainn** [comment]
Bullets are visible to me on both desktop and mobile. Are you using iPhone & mac?

**Comment by rjurney** [comment]
Can you share a screenshot? Yes, I'm on Mac Chrome. Here is Mac Safari:

<img width="1436" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/ba01c354-8bcc-4ee8-9e8e-cd19b23ef1d3">
