### ISSUE TITLE
Make indentation of the headers and the text the same - or at least similar - on wider screens

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#24]
@sammjainn can you please fix it so the indentation isn't so severe here when the browser is really wide? The headings are really far left on Chrome on my Macbook Pro.

<img width="1904" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/680e652b-daac-4b4e-b8e4-0ba20c831b02">

You can see here it works ok if it isn't so wide - but many Mac users maximize their browsers.

<img width="1432" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/02d89b0c-432d-417e-9cae-425f0318ca1e">

**Comment by rjurney** [comment]
@sammjainn this is still an issue with widescreen on a Macbook Pro. I think maybe these should be centered if they can't have the same indent as the text paragraphs? I'd prefer they be inline with the text

<img width="1904" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/9618e4ed-5b64-4a05-898d-981319942e1a">

<img width="1904" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/f66d5c0b-bff3-4f09-8e77-779ae0ac1d0a">

**Comment by rjurney** [comment]
@sammjainn 

<img width="1904" alt="image" src="https://github.com/Graphlet-AI/graphlet-ai.github.io/assets/42149/eb4bbf86-0a22-4bf5-b627-230deba64dd8">

**Comment by sammjainn** [comment]
Hi, I will work on these tomorrow and let you know once done
