### ISSUE TITLE
Remove currently unused header elements - and / or - center header

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#3]
Not all of these pages are ready, so I want to ship a single page website. That means removing the crossed out items from below:

![image](https://user-images.githubusercontent.com/42149/223853022-a5a210f8-d0e5-4906-b153-3c360892e57e.png)

Update: I removed the extra stuff and now it is not centered. Can you please center it again?

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/42149/223915582-c1b389ca-0c36-4894-90e3-3abc128b1683.png">

**Comment by sammjainn** [comment]
Which ones do you want to be shown? Both the images indicate different tabs

**Comment by rjurney** [comment]
I see. I want Blog and Github to show up. Contact can come later. Thanks!
