### ISSUE TITLE
Fix repeating background image in darker blue introduction region

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#5]
If you look at the background image here with my Chrome browser on a Macbook Pro from a few years ago with the maximum width of the page, the background image repeats from left to right. I want it to scale like...

![image](https://user-images.githubusercontent.com/42149/223855356-96cea67b-b0c3-42f2-96eb-24c19d496350.png)

the background image in the lighter background section does :)

<img width="1826" alt="image" src="https://user-images.githubusercontent.com/42149/223855087-e34d9b00-3620-4f82-ba8a-31cdbe744edd.png">

**Comment by sammjainn** [comment]
The image has torn design on its top and bottom. We can either have torn effect on both top and bottom, or we can have non-repeating image with only the top torn. This is due to background-size property -> contain & cover.

**Comment by rjurney** [comment]
Let's just keep both torn and let it repeat.
