### ISSUE TITLE
Add my own favicons in assets/icons - do use .ico format also

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#7]
I created some favicons in the icons folder, can you make these work so I don't get an error and they show in the browser bar? I do want to use .ico format as well as .png as sometimes it addresses bugs.

**Comment by sammjainn** [comment]
Unable to see any such favicons in the folder. Are you sure you merged these changes?

**Comment by rjurney** [comment]
@sammjainn Ok! There are now the following files:

* https://github.com/Graphlet-AI/graphlet-ai.github.io/blob/main/assets/icons/graphlet_logo.svg

![Graphlet SVG Logo](https://github.com/Graphlet-AI/graphlet-ai.github.io/blob/main/assets/icons/graphlet_logo.svg)

* https://github.com/Graphlet-AI/graphlet-ai.github.io/blob/main/assets/icons/favicon.ico
