### ISSUE TITLE
Links, as in <a href=“”> do not work anywhere in the page’s content

### ISSUE THREAD

**Issue by rjurney** [Graphlet-AI/graphlet-ai.github.io#8]
The links anywhere in the content section do not click, do not work. I need them to work :)

<img width="1826" alt="image" src="https://user-images.githubusercontent.com/42149/223857401-1ef187fe-5fc6-4f0d-a99b-fe1dd8d859fd.png">

**Comment by sammjainn** [comment]
They are working for me. Updated them to open in new tab
